stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: gourab/docker-react
  AWS_ACCESS_KEY: $AWS_ACCESS_KEY
  AWS_SECRET_KEY: $AWS_SECRET_KEY

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $DOCKER_IMAGE -f Dockerfile.dev .

deploy:
  stage: deploy
  image: python:latest
  only:
    - master
  script:
    - pip install awscli
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY
    - aws configure set aws_secret_access_key $AWS_SECRET_KEY
    - aws configure set default.region eu-north-1
    - aws s3 cp . s3://elasticbeanstalk-eu-north-1-911167921077/frontend --recursive
    - aws elasticbeanstalk create-application-version --application-name frontend --source-bundle S3Bucket="elasticbeanstalk-eu-north-1-911167921077",S3Key="AKIA5IJOXDO2XZUTXGSH" --version-label v1
    - aws elasticbeanstalk update-environment --environment-name Frontend-env --version-label v1
