services:
  - docker:dind
build_image:
  stage: build
  image: docker:latest
  before_script:
   - docker build -t gourab/docker-react -f Dockerfile.dev .
  script:
    - docker run -e CI=true gourab/docker-react npm run test